### ISSUE TITLE
Status unavailable repetition still present

### ISSUE THREAD

**Issue by pgwillia** [datacite/cheetoh#24]
Note `_status: unavailable | unavailable | withdrawn` and `recorded_at: Fri, 14 Dec 2018 22:24:57 GMT` from a vcr tape recorded today.

```
    body:
      encoding: ASCII-8BIT
      string: |-
        success: doi:10.21967/fk2-wkf8-4218
        _target: http://localhost/items/887f369a-6386-4814-ad6c-4bbab4908786
        datacite: <?xml version="1.0" encoding="UTF-8"?>%0A<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">%0A  <identifier identifierType="DOI">10.21967/FK2-WKF8-4218</identifier>%0A  <creators>%0A    <creator>%0A      <creatorName>Joe Blow</creatorName>%0A    </creator>%0A  </creators>%0A  <titles>%0A    <title>Different Title</title>%0A  </titles>%0A  <publisher>University of Alberta Libraries</publisher>%0A  <publicationYear>2017</publicationYear>%0A  <resourceType resourceTypeGeneral="Text">Text/Book</resourceType>%0A  <dates>%0A    <date dateType="Issued">2017</date>%0A  </dates>%0A  <version/>%0A  <descriptions>%0A    <description descriptionType="Abstract"/>%0A  </descriptions>%0A</resource>%0A
        _profile: datacite
        _datacenter: CISTI.UAL
        _export: no
        _created: 1544826292
        _updated: 1544826297
        _status: unavailable | unavailable | withdrawn
    http_version: 
  recorded_at: Fri, 14 Dec 2018 22:24:57 GMT
```

I'm not sure why https://github.com/datacite/cheetoh/blob/b1cc77c9a29738005396ddcdaa4cc982b3cf6389/app/controllers/concerns/doiable.rb#L97 uses '%7' instead of `|`.  Could this be the problem?

This message may have been lost in the shuffle:
_Originally posted by @pgwillia in https://github.com/datacite/cheetoh/issues/23#issuecomment-445046885_

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h2ob)

**Comment by mfenner** [comment]
Can you clarify whether this is in `production` or `test`? We merged the changes into production only yesterday, as part of a bigger deploy.

We use `%7C` because of the `Rack::UTF8Sanitizer` used at https://github.com/datacite/cheetoh/blob/master/config/application.rb#L75

**Comment by pgwillia** [comment]
This continues to be against `ez.test.datacite.org` I'm not sure if this is `production` or `test` from your point of view.  We are [preparing for](https://github.com/ualbertalib/jupiter/issues/711) but haven't started using `ez.datacite.org`.


```
[ezid_removal.yml.txt](https://github.com/datacite/cheetoh/files/2687622/ezid_removal.yml.txt)

**Comment by kjgarza** [comment]
@pgwillia We implemented a fix in https://github.com/datacite/cheetoh/commit/0f26a09d0f9beaff1bb7ea59d504c0c9518474d0, could I borther you on checking if the error is still hapening to you?

**Comment by pgwillia** [comment]
@kjgarza I've reviewed.  The 'unavailable' repetition is no longer occurring, but the reason (not publicly released) isn't there

```
--- expected
+++ actual
@@ -1 +1,2 @@
-"unavailable | not publicly released"
+# encoding: ASCII-8BIT
+"unavailable"
```

```
http_interactions:
- request:
    method: post
    uri: https://ez.test.datacite.org/id/doi:10.21967/fk2-294e-3k73
    body:
      encoding: UTF-8
      string: |-
        datacite.creator: Joe Blow
        datacite.publisher: University of Alberta Libraries
        datacite.publicationyear: 2017
        datacite.title: Different Title
        _target: http://localhost/items/7f3c699e-c688-43d5-a555-451b27bcffe9
        _status: unavailable | not publicly released
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - ez.test.datacite.org
      Content-Type:
      - text/plain; charset=UTF-8
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 26 Feb 2019 16:42:14 GMT
      Content-Type:
      - text/plain; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Status:
      - 200 OK
      Cache-Control:
      - max-age=0, private, must-revalidate
      Vary:
      - Accept-Encoding
      Server:
      - nginx/1.15.8 + Phusion Passenger 6.0.1
    body:
      encoding: ASCII-8BIT
      string: |-
        success: doi:10.21967/fk2-294e-3k73
        _target: http://localhost/items/7f3c699e-c688-43d5-a555-451b27bcffe9
        datacite: <?xml version="1.0" encoding="UTF-8"?>%0A<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">%0A  <identifier identifierType="DOI">10.21967/FK2-294E-3K73</identifier>%0A  <creators>%0A    <creator>%0A      <creatorName>Joe Blow</creatorName>%0A    </creator>%0A  </creators>%0A  <titles>%0A    <title>Different Title</title>%0A  </titles>%0A  <publisher>University of Alberta Libraries</publisher>%0A  <publicationYear>2017</publicationYear>%0A  <resourceType resourceTypeGeneral="Text">Text/Book</resourceType>%0A  <dates>%0A    <date dateType="Issued">2017</date>%0A  </dates>%0A  <version/>%0A  <descriptions>%0A    <description descriptionType="Abstract"/>%0A  </descriptions>%0A</resource>%0A
        _profile: datacite
        _datacenter: CISTI.UAL
        _export: no
        _created: 1551199330
        _updated: 1551199334
        _status: unavailable
    http_version: 
  recorded_at: Tue, 26 Feb 2019 16:42:14 GMT
```
